























.build/nano328/DHTlib/dht.o : lib/DHTlib/dht.cpp
	@echo [93mDHTlib/dht.cpp[0m
	@mkdir -p .build/nano328/DHTlib
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/DHTlib/dht.cpp
include .build/nano328/DHTlib/dht.d



.build/nano328/DHTlib/libDHTlib.a : .build/nano328/DHTlib/dht.o
	@echo [92mLinking libDHTlib.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/nano328/LiquidCrystal_I2C/LiquidCrystal_I2C.o : lib/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp
	@echo [93mLiquidCrystal_I2C/LiquidCrystal_I2C.cpp[0m
	@mkdir -p .build/nano328/LiquidCrystal_I2C
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp
include .build/nano328/LiquidCrystal_I2C/LiquidCrystal_I2C.d



.build/nano328/LiquidCrystal_I2C/libLiquidCrystal_I2C.a : .build/nano328/LiquidCrystal_I2C/LiquidCrystal_I2C.o
	@echo [92mLinking libLiquidCrystal_I2C.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/nano328/DS1307RTC/DS1307RTC.o : lib/DS1307RTC/DS1307RTC.cpp
	@echo [93mDS1307RTC/DS1307RTC.cpp[0m
	@mkdir -p .build/nano328/DS1307RTC
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/DS1307RTC/DS1307RTC.cpp
include .build/nano328/DS1307RTC/DS1307RTC.d



.build/nano328/DS1307RTC/libDS1307RTC.a : .build/nano328/DS1307RTC/DS1307RTC.o
	@echo [92mLinking libDS1307RTC.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/nano328/Fat16/SdCard.o : lib/Fat16/SdCard.cpp
	@echo [93mFat16/SdCard.cpp[0m
	@mkdir -p .build/nano328/Fat16
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/Fat16/SdCard.cpp
include .build/nano328/Fat16/SdCard.d

.build/nano328/Fat16/Fat16.o : lib/Fat16/Fat16.cpp
	@echo [93mFat16/Fat16.cpp[0m
	@mkdir -p .build/nano328/Fat16
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/Fat16/Fat16.cpp
include .build/nano328/Fat16/Fat16.d



.build/nano328/Fat16/libFat16.a : .build/nano328/Fat16/SdCard.o .build/nano328/Fat16/Fat16.o
	@echo [92mLinking libFat16.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/nano328/Time/DateStrings.o : lib/Time/DateStrings.cpp
	@echo [93mTime/DateStrings.cpp[0m
	@mkdir -p .build/nano328/Time
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/Time/DateStrings.cpp
include .build/nano328/Time/DateStrings.d

.build/nano328/Time/Time.o : lib/Time/Time.cpp
	@echo [93mTime/Time.cpp[0m
	@mkdir -p .build/nano328/Time
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/Time/Time.cpp
include .build/nano328/Time/Time.d



.build/nano328/Time/libTime.a : .build/nano328/Time/DateStrings.o .build/nano328/Time/Time.o
	@echo [92mLinking libTime.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/nano328/Wire/utility/twi.o : /usr/share/arduino/libraries/Wire/utility/twi.c
	@echo [93mWire/utility/twi.c[0m
	@mkdir -p .build/nano328/Wire/utility
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/libraries/Wire/utility/twi.c
include .build/nano328/Wire/utility/twi.d






.build/nano328/Wire/Wire.o : /usr/share/arduino/libraries/Wire/Wire.cpp
	@echo [93mWire/Wire.cpp[0m
	@mkdir -p .build/nano328/Wire
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/Wire/Wire.cpp
include .build/nano328/Wire/Wire.d



.build/nano328/Wire/libWire.a : .build/nano328/Wire/utility/twi.o .build/nano328/Wire/Wire.o
	@echo [92mLinking libWire.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/nano328/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/nano328/arduino/wiring_pulse.d

.build/nano328/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/nano328/arduino/wiring_analog.d

.build/nano328/arduino/avr-libc/malloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo [93marduino/avr-libc/malloc.c[0m
	@mkdir -p .build/nano328/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/nano328/arduino/avr-libc/malloc.d

.build/nano328/arduino/avr-libc/realloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo [93marduino/avr-libc/realloc.c[0m
	@mkdir -p .build/nano328/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/nano328/arduino/avr-libc/realloc.d

.build/nano328/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/nano328/arduino/wiring_digital.d

.build/nano328/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/nano328/arduino/wiring_shift.d

.build/nano328/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/nano328/arduino/WInterrupts.d

.build/nano328/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/nano328/arduino/wiring.d






.build/nano328/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/nano328/arduino/IPAddress.d

.build/nano328/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/nano328/arduino/new.d

.build/nano328/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/nano328/arduino/CDC.d

.build/nano328/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/nano328/arduino/Tone.d

.build/nano328/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/nano328/arduino/USBCore.d

.build/nano328/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/nano328/arduino/Print.d

.build/nano328/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/nano328/arduino/main.d

.build/nano328/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/nano328/arduino/HID.d

.build/nano328/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/nano328/arduino/HardwareSerial.d

.build/nano328/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/nano328/arduino/WString.d

.build/nano328/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/nano328/arduino/Stream.d

.build/nano328/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/nano328/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/nano328/arduino/WMath.d



.build/nano328/arduino/libarduino.a : .build/nano328/arduino/wiring_pulse.o .build/nano328/arduino/wiring_analog.o .build/nano328/arduino/avr-libc/malloc.o .build/nano328/arduino/avr-libc/realloc.o .build/nano328/arduino/wiring_digital.o .build/nano328/arduino/wiring_shift.o .build/nano328/arduino/WInterrupts.o .build/nano328/arduino/wiring.o .build/nano328/arduino/IPAddress.o .build/nano328/arduino/new.o .build/nano328/arduino/CDC.o .build/nano328/arduino/Tone.o .build/nano328/arduino/USBCore.o .build/nano328/arduino/Print.o .build/nano328/arduino/main.o .build/nano328/arduino/HID.o .build/nano328/arduino/HardwareSerial.o .build/nano328/arduino/WString.o .build/nano328/arduino/Stream.o .build/nano328/arduino/WMath.o
	@echo [92mLinking libarduino.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/nano328/src/sketch.o : .build/nano328/src/sketch.cpp
	@echo [93msrc/sketch.cpp[0m
	@mkdir -p .build/nano328/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -Ilib/DHTlib -Ilib/LiquidCrystal_I2C -Ilib/LiquidCrystal_I2C/info -Ilib/DS1307RTC -Ilib/Fat16 -Ilib/Fat16/utility -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions -iquote src  -o $@ -c .build/nano328/src/sketch.cpp
include .build/nano328/src/sketch.d







.build/nano328/firmware.elf : .build/nano328/src/sketch.o .build/nano328/DHTlib/libDHTlib.a .build/nano328/LiquidCrystal_I2C/libLiquidCrystal_I2C.a .build/nano328/DS1307RTC/libDS1307RTC.a .build/nano328/Fat16/libFat16.a .build/nano328/Time/libTime.a .build/nano328/Wire/libWire.a .build/nano328/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/nano328/firmware.hex : .build/nano328/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/nano328/src/dependencies.d .build/nano328/arduino/dependencies.d .build/nano328/DHTlib/dependencies.d .build/nano328/LiquidCrystal_I2C/dependencies.d .build/nano328/Wire/dependencies.d .build/nano328/DS1307RTC/dependencies.d .build/nano328/Time/dependencies.d .build/nano328/Fat16/dependencies.d

all : .build/nano328/firmware.hex
	@true

